### ISSUE TITLE
may need to balance the container usage by changing the batch size

### ISSUE THREAD

**Issue by YanLiang1102** [oudalab/biryani#12]
@cegme @PhaniJella @ahalterman one thing to notice is the different containers not only have the same pattern of memory usage also there up and down time has the same pattern, which make me thinking we can make they consume different batch size like node 1 has batch size 400 , node 2 has batch size 500 and node 3 has 600 to make their schedule different and I think the cpu should be utilized better in this way

![yanli114](https://cloud.githubusercontent.com/assets/10291607/12703733/cbfa6a42-c80f-11e5-84dc-23f234a3d291.png)
![yanli116](https://cloud.githubusercontent.com/assets/10291607/12703734/ce13e448-c80f-11e5-9cce-f487c23667c5.png)

**Comment by ahalterman** [comment]
Good idea. Maybe so we don't have to hard-code it in each container, it can randomly vary the batch size each time. So each batch could be 500, plus a random number sampled from -200 to 200. Over time, that should make them end up on different schedules.

**Comment by YanLiang1102** [comment]
@ahalterman  actually Dr Grant suggest only run one container on kingston, since if u using more containers, it will still compete the limited resources, I think we might need to test one container with a big batch size or more containers with a small batch size can be better.
yeah random generate the size is a good idea.

**Comment by cegme** [comment]
@ahalterman @yanliang1102 I love the idea of dynamic batch sizes!!! And we can let each run measure the docs/sec and choose its own baseline.
