### ISSUE TITLE
Unable to parse remaining documents which are not a multiple of batch size

### ISSUE THREAD

**Issue by PhaniJella** [oudalab/biryani#13]
suppose say our batch size is 500 and our total documents are 756. 

every time we receive a message from rabbitmq queue, we are calling a function called dowork.
what dowork does is stores the message to the blockingqueue and we wrote a logic that if size of blocking queue is 500  or ideal time with out parsing is 1 min we start parsing the documents.

but the problem is, in this case as documents size is 756, after 1st iteration we parse 500 documents and remaining document size becomes 756-500 = 256.

in second iteration we we never reach the size of 500 as the documents remaining are only 256.!

**Comment by YanLiang1102** [comment]
What about giving it a timeout? Or some script checking how many stuff in the mainQUeue left?
