### ISSUE TITLE
Implement Logging

### ISSUE THREAD

**Issue by PhaniJella** [oudalab/biryani#2]
Implement logging to debug easily. Look at python logging!

**Comment by cegme** [comment]
This is not yet high priority but lets spin up a docker using the ELK stack, a combination of components including Elasticseach, Logstash and Kibana. We can set this server up to send log messages here. This will let us log across languages (Python + Java).

There is also a docker repo called [devianthony/docker-elk](https://github.com/deviantony/docker-elk) for this so we can launch these containers to handle the logging.

**Comment by cegme** [comment]
It seems like logging is correctly implemented on kingston. 
- [x]  Can you create a README so anyone using this can deploy their own logging system

Then we can close this issue.
