### ISSUE TITLE
Write dynamic batch sizing algorithm

### ISSUE THREAD

**Issue by ahalterman** [oudalab/biryani#24]
We want to change the batch size based on CPU and memory usage for the container. Hopefully this will make it more efficient, and it will definitely make things more interesting.

**Comment by PhaniJella** [comment]
In the first version of algorithm we not considering the size of the documents processed...! Modify the algorithm to for a batch executed how many sentences or bytes of data we are parsing. This might give us the better idea to dynamically re-size the batch
