### ISSUE TITLE
Output of the corenlp

### ISSUE THREAD

**Issue by PhaniJella** [oudalab/biryani#7]
What is the desired output we are looking form the corenlp? if we pass whole paragraph, right now to my understanding the output generated is sentence by sentence... like each sentence in the paragraph is being parsed not the whole paragraph. 

How the structure of the output should be formated and where and how to be stored. If we can get a sample format of the output it will be helpful.

**Comment by YanLiang1102** [comment]
Andy, yeah, that will be helpful, Phani, maybe there is another way, we can look at the source code of hypnos and see what api of corenlp it is using there

**Comment by PhaniJella** [comment]
Yan, that might be helpful.. even Dr. Grant suggested the same.

**Comment by ahalterman** [comment]
We can see an example of the input that Petrarch2 expects in this example/test file.

https://github.com/openeventdata/petrarch2/blob/master/petrarch2/tests/test_petrarch.py#L209

```
dict = {u'test123': {u'sents': {u'0': {u'content': text, u'parsed': parsed}},
                u'meta': {u'date': u'20010101'}}}
petrarch2.do_coding(dict,None)
```

`text` and `parse` are both strings.
